### PR TITLE
Upgrade Scala versions

### PR DESCRIPTION
**Pull request by jodersky**
~~(pending https://github.com/lihaoyi/geny/pull/17)~~
~~pending https://github.com/scala/scala-collection-compat/issues/413~~

### CODE REVIEW

**Comment by jodersky** [comment]
@anatoliykmetyuk, @lihaoyi, the utest and geny issues blocking this PR have been resolved, however now I'm running into another very strange incompatibility issue. It appears to be unrelated to the Scala 3 bump. Could it be some other binary compat issue with upstream depedencies?

```
$ mill core.js[2.12.10,1.0.0].test
[81/82] core.js[2.12.10,1.0.0].test.fastOptTest 
1 targets failed
core.js[2.12.10,1.0.0].test.fastOptTest org.scalajs.ir.IRVersionNotSupportedException: Failed to deserialize a file compiled with Scala.js 1.4 (supported up to: 1.0): /home/jodersky/.cache/coursier/v1/https/repo1.maven.org/maven2/org/scala-js/scalajs-library_2.12/1.4.0/scalajs-library_2.12-1.4.0.jar:/scala/Predef$DummyImplicit$.sjsir
org.scalajs.ir.IRVersionNotSupportedException: This version (1.4) of Scala.js IR is not supported. Supported versions are up to 1.0
```

**Comment by jodersky** [comment]
Bumping Scala JS to a newer version (1.4.0) fixes the issue

**Comment by lolgab** [comment]
@jodersky scala-collection-compat 2.4.0 is on Maven Central

**Comment by jodersky** [comment]
ok, retrying the build...

**Comment by lolgab** [comment]
@jodersky Opened a PR to your branch. I guess the `_2.13` hack is not needed anymore since now scala-collection-compat is released for 3.0.0-M3

**Comment by jodersky** [comment]
Yeah, I'm working on it as we speak. There's another issue however, which is that compat is not published for scalajs 0.6 it appears

**Comment by lolgab** [comment]
I dropped support for Scala.js 0.6 in the [PR I made to your branch](https://github.com/jodersky/upickle/pull/1)

**Comment by lihaoyi** [comment]
I dropped support for Scalajs 0.6 in fastparse and mainargs as well, I think Scala.js 1.x has been out for long enough by this point

**Comment by jodersky** [comment]
I think that dropping the compat dependency is good regardless of what we end up deciding on scalajs 0.6. There's no harm done in keeping scalajs 0.6 here while it works

**Comment by lihaoyi** [comment]
Works for me

**Comment by jodersky** [comment]
Travis is taking a long time (the build is still in queue as of this writing). FWIW, I ran all tests in a clean VM with openjdk 8, node 14 and clang 7, and everything passed.

**Comment by jodersky** [comment]
hooray, the build passed!

**Review by lihaoyi — APPROVED** [review]

**Comment by lolgab** [comment]
Version 1.2.3 going to Maven Central.

**Pull request merged**
